apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecast-partner-api
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: weatherforecast-svc
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: ssh://git@github.com/akinsanyaleke/weatherforecast-partner-api.git
      ref:
        branch: main
